# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.q = QtWidgets.QTextEdit(self.centralwidget)
        self.q.setGeometry(QtCore.QRect(140, 50, 491, 71))
        self.q.setObjectName("q")
        self.a = QtWidgets.QTextEdit(self.centralwidget)
        self.a.setGeometry(QtCore.QRect(120, 200, 551, 321))
        self.a.setObjectName("a")
        self.s = QtWidgets.QPushButton(self.centralwidget)
        self.s.setGeometry(QtCore.QRect(680, 60, 93, 28))
        self.s.setObjectName("s")
        self.e = QtWidgets.QPushButton(self.centralwidget)
        self.e.setGeometry(QtCore.QRect(680, 110, 93, 28))
        self.e.setObjectName("e")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(370, 10, 71, 21))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.s.setText(_translate("MainWindow", "查询"))
        self.e.setText(_translate("MainWindow", "退出"))
        self.lineEdit.setText(_translate("MainWindow", "搜题软件"))
